# General
APP_NAME: EXO
APP_FONT: Inter
APP_SPLASH: "#18181b"
DESIGN_NAME: react-exo-ui
DESIGN_VERSION: 1.1.27
STORE_VERSION: 1

# Services
EVOLU_RELAY: wss://free.evoluhq.com

# Native
PACKAGE_IOS: com.exo.ios
PACKAGE_ANDROID: com.exo.android
PACKAGE_DESKTOP: com.exo.desktop

# Web
LINK_HOMEPAGE: https://exo.ult.dev
LINK_DISCORD: https://discord.kat.tax
LINK_X: https://x.com/theultdev

# Translations
LANG_EN: English
LANG_ES: Español
LANG_RU: Русский
LANG_JA: やまと
LANG_KO: 한국어
LANG_AR: عربي
