# General
APP_NAME: EXO
APP_DISPLAY_NAME: EXO

# Design
FONT_NAME: InterVariable

# Data
SYNC_HOST: 'wss://free.evoluhq.com'
STORE_VERSION: 1.0

# Web
LINK_DOCS: https://exo.ult.dev
LINK_STORYBOOK: https://exo.fig.run
LINK_DISCORD: https://discord.gg/KpMZVKmfnb
LINK_GITHUB: https://github.com/kat-tax/exo
LINK_X: https://x.com/theultdev

# Native
PACKAGE_IOS: com.exo.ios
PACKAGE_MACOS: com.exo.macos
PACKAGE_ANDROID: com.exo.android
PACKAGE_WINDOWS: com.exo.windows

# Translations
LANG_EN: English
LANG_ES: Español
LANG_RU: Русский
LANG_JA: 日本語
LANG_KO: 한국어
LANG_AR: عربي
