# General
 DISPLAY_NAME: EXO STUDIO
APP_NAME: EXO
APP_VERSION: 1.0.0

# Design
 PACKAGE_NAME: react-exo-ui
PACKAGE_VERSION: 1.0.137
FONT_NAME: Inter

# State
 STORE_VERSION: 1

# Native
 IOS: com.exo.ios
MACOS: com.exo.macos
ANDROID: com.exo.android
WINDOWS: com.exo.windows

# Web
 DOCS: https://exo.ult.dev
FIGMA: https://www.figma.com/file/DFmPlavFWyMaYJtoGLhGz3
STORYBOOK: https://exo.fig.run
DISCORD: https://discord.gg/KpMZVKmfnb
GITHUB: https://github.com/kat-tax/exo
X: https://x.com/theultdev