# General
APP_NAME: EXO
FONT_NAME: Inter
DESIGN_NAME: react-exo-ui
DESIGN_VERSION: 1.1.18
STORE_VERSION: 1

# Services
EVOLU_RELAY: wss://free.evoluhq.com

# Apps
IOS: com.exo.ios
MACOS: com.exo.macos
ANDROID: com.exo.android
WINDOWS: com.exo.windows

# Web
LINK_DOCS: https://exo.ult.dev
LINK_FIGMA: https://www.figma.com/file/DFmPlavFWyMaYJtoGLhGz3
LINK_STORYBOOK: https://exo.fig.run
LINK_DISCORD: https://discord.gg/KpMZVKmfnb
LINK_GITHUB: https://github.com/kat-tax/exo
LINK_X: https://x.com/theultdev

# Translations
LANG_EN: English
LANG_ES: Español
LANG_RU: Русский
LANG_JA: やまと
LANG_KO: 한국어
LANG_AR: عربي