packages:
  - build/**
  - client/**
  - design/**
  - torrent # temporary
  - '!**/test/**'

catalog:
  '@lingui/babel-plugin-lingui-macro': ^5.5.0
  '@lingui/cli': ^5.5.0
  '@lingui/conf': ^5.5.0
  '@lingui/core': ^5.5.0
  '@lingui/macro': ^5.5.0
  '@lingui/react': ^5.5.0
  '@lingui/vite-plugin': ^5.5.0
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  react: 19.1.0
  react-dom: 19.1.0
  react-exo: 0.20.20
  react-native: 0.80.2
  react-native-reanimated: ^3.19.1
  react-native-svg: ^15.13.0
  react-native-unistyles: ^3.0.19
  react-native-vision-camera: ^4.7.3
  react-native-web: 0.21.2
  typescript: ^5.9.2

catalogMode: manual

cleanupUnusedCatalogs: true

minimumReleaseAge: 1440
