packages:
  - build/**
  - client/**
  - design/**
  - '!**/test/**'

catalog:
  '@lingui/babel-plugin-lingui-macro': ^5.5.0
  '@lingui/cli': ^5.5.0
  '@lingui/conf': ^5.5.0
  '@lingui/core': ^5.5.0
  '@lingui/macro': ^5.5.0
  '@lingui/react': ^5.5.0
  '@lingui/vite-plugin': ^5.5.0
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  react: 19.1.0
  react-dom: 19.1.0
  react-exo: 0.20.19
  react-native: 0.80.2
  react-native-reanimated: ^3.19.1
  react-native-svg: ^15.13.0
  react-native-unistyles: ^3.0.17
  react-native-web: 0.21.1
  typescript: ^5.9.2

catalogMode: prefer

cleanupUnusedCatalogs: true

minimumReleaseAge: 1440

patchedDependencies:
  '@legendapp/list@2.0.14': patches/@legendapp__list@2.0.14.patch
