# Workspace packages
packages:
  - build/**
  - client/**
  - native/**
  - design/**
  - locales/**
  - '!**/test/**'

# Prevent zero-days
minimumReleaseAge: 1440

# Catalog config
catalogMode: prefer
cleanupUnusedCatalogs: true

# Common dependencies
catalog:
  react: "19.1.0"
  react-dom: "19.1.0"
  react-exo: "0.20.17"
  react-native: "0.80.2"
  react-native-web: "0.21.1"
  react-native-svg: "^15.13.0"
  react-native-unistyles: "^3.0.12"
  react-native-reanimated: "^3.19.1"
  typescript: "^5.9.2"
  "@types/react": "^19.1.13"
  "@types/react-dom": "^19.1.9"
  "@lingui/cli": "^5.5.0"
  "@lingui/conf": "^5.5.0"
  "@lingui/core": "^5.5.0"
  "@lingui/macro": "^5.5.0"
  "@lingui/react": "^5.5.0"
  "@lingui/vite-plugin": "^5.5.0"
  "@lingui/babel-plugin-lingui-macro": "^5.5.0"
