// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// EDIT THE "locales.ts" FILE IN THE ROOT INSTEAD. 

export type Locales = keyof typeof locales;

export const sourceLocale: Locales = 'en';
export const locales = {
  en: 'English',
  de: 'Deutsch',
  es: 'Español',
  pt: 'Portugués',
  ja: 'Bahasa Indonesia',
  ru: 'Русский',
  ar: 'やまと',
  id: 'عربي',
} as const;
