# General
APP_NAME: EXO

# Library
LIB_NAME: react-exo
LIB_VERSION: 1.0.0

# Native
PACKAGE_NAME: com.ult.exo

# State
STORE_VERSION: 1

# Navigation
NAV_MENU_WIDTH_MIN: 60
NAV_MENU_WIDTH_MAX: 200
NAV_MENU_BREAKPOINT: 600
