# General
APP_NAME: EXO
APP_DISPLAY_NAME: EXO

# Library
LIB_NAME: react-exo
LIB_VERSION: 1.2.0

# State
STORE_VERSION: 1

# Native
PACKAGE_IOS: com.exo.ios
PACKAGE_ANDROID: com.exo.android
PACKAGE_WINDOWS: com.exo.windows

# Links
LINK_DOCS: https://exo.ult.dev
LINK_STORYBOOK: https://exo.fig.run
LINK_DISCORD: https://discord.gg/KpMZVKmfnb
LINK_GITHUB: https://github.com/kat-tax/exo
LINK_X: https://x.com/theultdev

# Fonts
FONT_ID: inter
FONT_NAME: Inter
